### ISSUE TITLE
可以把你的项目加到《请收下学长的代码》里么

### ISSUE THREAD

**Issue by gaocegege** [mjc0608/Homework-1#2]
http://gaocegege.com/Blog/%E9%9A%8F%E7%AC%94/newyear/
如题，供学弟学妹参考~？

**Comment by wizardforcel** [comment]
。。。可是这门课的作业太容易变了

**Comment by codeworm96** [comment]
期待马神分享。
看来这项活动已经成为软院传统了，觉得可以用 gitpages 单独设一个资源站。

**Comment by mjc0608** [comment]
。。。随意吧不过我记得里面有一些代码巨烂

**Comment by gaocegege** [comment]
~
